import type { Metadata } from "next";
import AppBar from "../components/AppBar/AppBar";
import Footer from "../components/Footer/Footer";
import { Geist, Geist_Mono } from "next/font/google";
import AppContext from "../Context/AppContext";
// import { UserProvider } from "@auth0/nextjs-auth0/client";

// import AuthWrapper from "../Context/NextAuthProvider";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GearCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <UserProvider > */}
          <AppContext>
            <NextTopLoader height={5} showSpinner={false} />
            <AppBar />
            {children}
            <Footer />
          </AppContext>
        {/* </UserProvider> */}
      </body>
    </html>
  );
}
